### ISSUE TITLE
Util::serialize: Using "wb" doesn't lead to appended writes

### ISSUE THREAD

**Issue by k00ni** [sweetrdf/quickRdfIo#3]
It seems that using `wb` in `Util::serialize` https://github.com/sweetrdf/quickRdfIo/blob/master/src/quickRdfIo/Util.php#L241 doesn't allow appending writes.

Here is my code:

```php
Util::serialize(new GenericQuadIterator($quads), 'n-triples', $filename, $nsList);
// code is inside a function and called in a loop
```
When using `wb` only the latest quad is shown in the file. After switching to `a`, it works as expected.

Did I miss something? If my assumption is correct, I can provide a PR.

**Comment by zozlak** [comment]
Yes and no.
The thing is when the output location is provided as a string, there is no way to indicate how do you want to open the file with a given file name - for (over)write of for append. For me the more intuitive behaviour is to open for an (over)write but of course it's a matter of taste and there will be always someone who sees it opposite. 

In the example you're describing I would assume a following syntax:
```php
$output = fopen('filename', 'a');
yourLoop {
   (...)
   Util:serialize(new GenericQuadIterator($quads), 'n-triples', $output, $nsList);
   (...)
}
fclose($output);
```
or (which will work perfectly fine with PHP automatically closing the file handle on the `Util::serialize()` end)
```php
yourLoop {
   (...)
   Util:serialize(new GenericQuadIterator($quads), 'n-triples', fopen('filename', 'a'), $nsList);
   (...)
}
```

**Comment by k00ni** [comment]
Ah, I see. I used a string for `$output`, like `/tmp/my-data.ttl`. Handling `fopen` myself seems the way to go.
