### ISSUE TITLE
How to parse N3 files?

### ISSUE THREAD

**Issue by k00ni** [sweetrdf/quickRdfIo#5]
What parser do I have to use to parse N3 file?

```turtle
@prefix lov:   <http://lov.okfn.org/dataset/lov/> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .

<>      a          foaf:Organization , foaf:Person ;
        foaf:name  "Ilaria Baroni" .
```
If I use NQuadsParser it throws an exception:

```php

$dataFactory = new DataFactory();
$parser = new NQuadsParser($dataFactory, true, NQuadsParser::MODE_TRIPLES);
$quads = $parser->parse(file_get_contents($n3Filepath));

foreach ($quads as $quad) {
    echo "$quad";
}

/*
Fatal error: Uncaught quickRdfIo\RdfIoException: Can't parse line 1: @prefix lov: <http://lov.okfn.org/dataset/lov/> .
 in /govi/vendor/sweetrdf/quick-rdf-io/src/quickRdfIo/NQuadsParser.php:264
Stack trace:
#0 [internal function]: quickRdfIo\NQuadsParser->quadGenerator()
#1 /govi/vendor/sweetrdf/quick-rdf-io/src/quickRdfIo/NQuadsParser.php(247): Generator->valid()
#2 /govi/bin/read-linked-open-vocabularies(59): quickRdfIo\NQuadsParser->valid()
#3 {main}
  thrown in /govi/vendor/sweetrdf/quick-rdf-io/src/quickRdfIo/NQuadsParser.php on line 264
*/
```

If I use Utils::parse nothing gets parsed at all:

```php

$dataFactory = new DataFactory();
$iterator = Util::parse($n3Filepath, $dataFactory, 'n3');

// $iterator is null! the following fails
foreach ($iterator as $quad) {
    echo "$quad";
}
```

I might have overlooked something.

**Comment by k00ni** [comment]
**To solve this I have to tell him its Turtle and provide a base URI:**

```
$dataFactory = new DataFactory();
$iterator = Util::parse($n3Filepath, $dataFactory, 'turtle', 'http://foo/');

foreach ($iterator as $quad) {
    echo "$quad";
}
```

Thanks @zozlak!

**Comment by zozlak** [comment]
In details:

* You're trying to parse a turtle so it can't be parsed as n-quads.
* If you try to parse as turtle (or n3), the hardf is used under the hood and you run into the https://github.com/pietercolpaert/hardf/issues/37 (lack of base URL leading to an empty subject leading to the hardf silently not parsing any triples).

All possible solutions go as follows:

* Provide the base URL:
  * If using `quickRdfIo\Util::parse()`, pass it as the 4th parameter (as you propose above)
  * if Using `quickRdfIo\TriGParser`, include it in the `$options` passed to the constructor, e.g. `$parser = new quickRdfIo\TriGParser($dataFactory, ['documentIRI' => $baseURL])`
* Adjust the hardf library - see the https://github.com/pietercolpaert/hardf/issues/37
