### ISSUE TITLE
How to handle misleading datatype annotation?

### ISSUE THREAD

**Issue by k00ni** [sweetrdf/quickRdfIo#8]
A misleading datatype annotation is a datatype which doesn't match with the object value. For instance: value is a long text (string) and datatype says `xsd:dateTime`. Parsing doesn't fail, but later on it might lead to failure. See the following example:

ntriples file of an ontology: http://archivo.dbpedia.org/download?o=http%3A%2F%2Fvocab.linkeddata.es%2Fdatosabiertos%2Fdef%2Furbanismo-infraestructuras%2Fcallejero&f=nt

It contains the following triple (shortened):

```
<http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero> 
    <http://www.w3.org/2000/01/rdf-schema#comment> 
        "Este [...] de localizaci\u00F3n\n\t\t"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
```

For whatever reason this object got the datatype `xsd:dateTime`. When loading it with quickRdfIo everything is fine, but when importing it into an EasyRdf `Graph` instance, an `DateMalformedStringException` is risen because EasyRdf tries to transform it into an actual `\DateTime` instance.

**How do we handle such cases?** Is there anything we can do on the "parser"-level? Another approach might be: do nothing, let the client/middleware handle semantically-invalid data. That means, "fix" EasyRdf and not quickRdfIo.

**Comment by zozlak** [comment]
I would just keep the current behaviour of not performing any validation. This is actually in line with the W3C's [RDF concepts](https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal) which says that a literal's value is:

> If the literal's datatype IRI is in the set of recognized datatype IRIs, let d be the referent of the datatype IRI.
> - If the literal's lexical form is in the lexical space of d, then the literal value is the result of applying the lexical-to-value mapping of d to the lexical form.
> - Otherwise, the literal is ill-typed and no literal value can be associated with the literal. Such a case produces a semantic inconsistency but is not syntactically ill-formed. Implementations MUST accept ill-typed literals and produce RDF graphs from them. Implementations MAY produce warnings when encountering ill-typed literals.

In this case we indeed have a datatype in the set of recognized datatype IRIs (`xsd:dateTime`) with a lexical form outside of the `xsd:dateTime` [lexical space](https://www.w3.org/TR/xmlschema-2/#dateTime) so the last point of the citation above applies (it MUST be accepted but a warning could be generated).

For me it's up to the higher level code to decide how to proceed with that.
